name: Tests RAG

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Post Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances de test
        run: |
pip install streamlit groq sentence-transformers pypdf rank-bm25 pinecone pytest
      - name: Lancer les tests
        run: pytest test_chunker.py test_auth.py test_pipeline.py -v
